spring:
  application:
    name: particulate
  datasource:
    url: jdbc:mariadb://localhost:3006/airquality?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: Root123!@#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
