spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/particulate?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root

server:
  port: 8080
  servlet:
    jsp:
      init-parameters:
        development: true

webhook:
  url: http://localhost:8080/webhook

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.exem.particulate.domain

logging:
  level:
    root: info
  charset:
    console: UTF-8
    file: UTF-8
